# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic-location-group.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynamic-location-group.proto',
  package='distributed_match_engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x64ynamic-location-group.proto\x12\x18\x64istributed_match_engine\"\xf3\x01\n\nDlgMessage\x12\x0b\n\x03ver\x18\x01 \x01(\r\x12\r\n\x05lg_id\x18\x02 \x01(\x04\x12\x14\n\x0cgroup_cookie\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\x04\x12=\n\x08\x61\x63k_type\x18\x05 \x01(\x0e\x32+.distributed_match_engine.DlgMessage.DlgAck\x12\x0f\n\x07message\x18\x06 \x01(\t\"O\n\x06\x44lgAck\x12\x18\n\x14\x44LG_ACK_EACH_MESSAGE\x10\x00\x12\x1b\n\x17\x44LG_ASY_EVERY_N_MESSAGE\x10\x01\x12\x0e\n\nDLG_NO_ACK\x10\x02\"=\n\x08\x44lgReply\x12\x0b\n\x03ver\x18\x01 \x01(\r\x12\x0e\n\x06\x61\x63k_id\x18\x02 \x01(\x04\x12\x14\n\x0cgroup_cookie\x18\x03 \x01(\t2o\n\x12\x44ynamicLocGroupApi\x12Y\n\x0bSendToGroup\x12$.distributed_match_engine.DlgMessage\x1a\".distributed_match_engine.DlgReply\"\x00\x62\x06proto3'
)



_DLGMESSAGE_DLGACK = _descriptor.EnumDescriptor(
  name='DlgAck',
  full_name='distributed_match_engine.DlgMessage.DlgAck',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DLG_ACK_EACH_MESSAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DLG_ASY_EVERY_N_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DLG_NO_ACK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=223,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_DLGMESSAGE_DLGACK)


_DLGMESSAGE = _descriptor.Descriptor(
  name='DlgMessage',
  full_name='distributed_match_engine.DlgMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ver', full_name='distributed_match_engine.DlgMessage.ver', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lg_id', full_name='distributed_match_engine.DlgMessage.lg_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_cookie', full_name='distributed_match_engine.DlgMessage.group_cookie', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='distributed_match_engine.DlgMessage.message_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack_type', full_name='distributed_match_engine.DlgMessage.ack_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='distributed_match_engine.DlgMessage.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DLGMESSAGE_DLGACK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=302,
)


_DLGREPLY = _descriptor.Descriptor(
  name='DlgReply',
  full_name='distributed_match_engine.DlgReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ver', full_name='distributed_match_engine.DlgReply.ver', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack_id', full_name='distributed_match_engine.DlgReply.ack_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_cookie', full_name='distributed_match_engine.DlgReply.group_cookie', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=365,
)

_DLGMESSAGE.fields_by_name['ack_type'].enum_type = _DLGMESSAGE_DLGACK
_DLGMESSAGE_DLGACK.containing_type = _DLGMESSAGE
DESCRIPTOR.message_types_by_name['DlgMessage'] = _DLGMESSAGE
DESCRIPTOR.message_types_by_name['DlgReply'] = _DLGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DlgMessage = _reflection.GeneratedProtocolMessageType('DlgMessage', (_message.Message,), {
  'DESCRIPTOR' : _DLGMESSAGE,
  '__module__' : 'dynamic_location_group_pb2'
  # @@protoc_insertion_point(class_scope:distributed_match_engine.DlgMessage)
  })
_sym_db.RegisterMessage(DlgMessage)

DlgReply = _reflection.GeneratedProtocolMessageType('DlgReply', (_message.Message,), {
  'DESCRIPTOR' : _DLGREPLY,
  '__module__' : 'dynamic_location_group_pb2'
  # @@protoc_insertion_point(class_scope:distributed_match_engine.DlgReply)
  })
_sym_db.RegisterMessage(DlgReply)



_DYNAMICLOCGROUPAPI = _descriptor.ServiceDescriptor(
  name='DynamicLocGroupApi',
  full_name='distributed_match_engine.DynamicLocGroupApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=367,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendToGroup',
    full_name='distributed_match_engine.DynamicLocGroupApi.SendToGroup',
    index=0,
    containing_service=None,
    input_type=_DLGMESSAGE,
    output_type=_DLGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DYNAMICLOCGROUPAPI)

DESCRIPTOR.services_by_name['DynamicLocGroupApi'] = _DYNAMICLOCGROUPAPI

# @@protoc_insertion_point(module_scope)
